### ISSUE TITLE
Fix/simplify/robustify generate_path_metadata method

### ISSUE THREAD

**Issue by watucker** [cedadev/rabbit-index-ingest#23]
Method in question:

https://github.com/cedadev/rabbit-index-ingest/blob/37e6739d3a73adc22c9861e15c6a3f41d68c619a/rabbit_indexer/utils/path_tools.py#L120

`link` = is link on the file system (already the case with is_list)
`path` is just the given path
`archive_path` should never be null = the link location if link is true, or the path if not

`storage_path` (which would include spot names) is never put in the index

This logic should be documented in this method's docstring, and the logic should be updated.

There may be some useless stuff happening in `SpotMapping.get_archive_path` so we could simplify that.

**Comment by rhysrevans3** [comment]
Just for clarification:

1. If it's a spot `archive_path` should equal `path`?
2. If `realpath` starts with `datacenter` it's a spot?

**Comment by gap736uk** [comment]
@rhysrevans3  - here's a couple of examples for you:

```
os.path.realpath('/badc/')
'/datacentre/archiveroots/archive/badc'
os.path.realpath('/badc/ukmo-rad-hires')
'/datacentre/archvol5/qb186/archive/ukmo-rad-hires'
```
cf with:
/badc/picasso/data/bae-146/c075-jan-23 -> /badc/faam/data/2018/c075-jan-23
which gives us:
```
>>> os.path.realpath('/badc/faam/data/2018/c075-jan-23')
'/datacentre/archvol5/qb175/archive/faam/data/2018/c075-jan-23'
```
i.e. realpath is _always_ resolving to something under /datacentre because that is actually where the data are....

_abspath_, though...  
```
>>> os.path.abspath('/badc/faam/data/2018/c075-jan-23')
'/badc/faam/data/2018/c075-jan-23'
>>> os.path.abspath('/badc/')
'/badc'
```

**Comment by gap736uk** [comment]
Still need to check what we get for the following cases:
 - relative path symlinking
 - symlinking to files, not directories
 - symlinks lower down which are to storage extentions

**Comment by gap736uk** [comment]
ok.. i've done some tests... lines of output are:
```
<path to test>|<comment line about the path>
<result of os.path.abspath> | <result of os.path.realpath>
```
```
/badc|top level path
/badc|/datacentre/archiveroots/archive/badc
/badc/ukmo-rad-hires|path to fileset top level
/badc/ukmo-rad-hires|/datacentre/archvol5/qb186/archive/ukmo-rad-hires
/badc/picasso/data/bae-146|path to folder which contains symlinks
/badc/picasso/data/bae-146|/datacentre/archvol5/qb172/archive/spot-48180-picasso/data/bae-146
/badc/picasso/data/bae-146/c075-jan-23/|symlinked dir
/badc/picasso/data/bae-146/c075-jan-23|/datacentre/archvol5/qb175/archive/faam/data/2018/c075-jan-23
/badc/cmip5/data/cmip5/output1/MOHC/HadCM3/historical/day/atmos/day/r10i1p1/latest/tas/tas_day_HadCM3_historical_r10i1p1_18591201-18841130.nc|path to symlinked file
/badc/cmip5/data/cmip5/output1/MOHC/HadCM3/historical/day/atmos/day/r10i1p1/latest/tas/tas_day_HadCM3_historical_r10i1p1_18591201-18841130.nc|/datacentre/archvol5/qb178/archive/spot-390/day/atmos/day/r10i1p1/files/tas_20110728/tas_day_HadCM3_historical_r10i1p1_18591201-18841130.nc```

**Comment by rhysrevans3** [comment]
- ### top level path
  - path: `/badc`
  - archive_path: `/badc`

- ### path to fileset top level
  - path: `/badc/ukmo-rad-hires`
  - archive_path: `/badc/ukmo-rad-hires`

- ### path to folder which contains symlinks
  - path: `/badc/ncas-observations/data/man-radar-1290mhz/previous-versions/2013/08`
  - archive_path: `/badc/ncas-observations/data/man-radar-1290mhz/previous-versions/2013/08`

- ### symlinked dir
  - path: `/badc/ncas-observations/data/man-radar-1290mhz/previous-versions/2013/08/31`
  - archive_path: `/badc/microscope/data/man-radar-1290mhz/20130831`

- ### storage extensions
  - path: `/badc/ecmwf-e40/data/gg`
  - archive_path: `/badc/ecmwf-e40/data/gg`

- ### relative path symlinks
  - path: `/badc/cmip5/data/cmip5/output1/MOHC/HadCM3/historical/day/atmos/day/r10i1p1/latest/huss/huss_day_HadCM3_historical_r10i1p1_18591201-18841130.nc`
  - archive_path: `/badc/cmip5/data/cmip5/output1/MOHC/HadCM3/historical/day/atmos/day/r10i1p1/files/huss_20110728/huss_day_HadCM3_historical_r10i1p1_18591201-18841130.nc`

- ### spot with symlinks
  - path: `/badc/ukmo-nimrod/data/single-site/wardon-hill/raw-dual-polar`
  - archive_path: `/badc/ukmo-nimrod/data/single-site/wardon-hill/raw-dual-polar`

- ### symlink in spots
  - path: `/badc/ukmo-nimrod/data/single-site/wardon-hill/raw-dual-polar/2018`
  - archive_path: `/badc/ukmo-nimrod/data/single-site/.storage_by_year/2018/wardon-hill/raw-dual-polar/2018`

This code currently works for these examples:

```
from pathlib import Path

path = Path(path)

link = path.is_symlink()
archive_path = path
if link:
    link_path = os.readlink(path)
    if not link_path.startswith('/datacentre'):
        archive_path = link_path
    elif link_path.startswith(".."):
        count = link_path.count("../")
        link_path = link_path.lstrip("./")
        archive_path = path.parents[count] / link_path
```

Are there any other edge cases? @gap736uk @spepler @watucker
